apiVersion: v1
kind: Service
metadata:
  name: licomart-backend
  namespace: licomart
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
